"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2025]  # Arbitrary atributes, matrix will go through all permutations!
        dotnet: ["8.0.x", "9.0.x"]
      fail-fast: false
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Build
        run: >
          dotnet build src/HelloWorld/HelloWorld.csproj
          --configuration Release

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-world-${{ matrix.os }}-${{ matrix.dotnet }}
          path: src/HelloWorld/bin/Release/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifact
      - name: Simulate deploy
        run: |
          echo "Deploying the following files:"
          ls ./artifact
          echo "Deploy complete."
